version: 0.0
os: linux
files:
  - source: target
    destination: /app
  - source: scripts
    destination: /app/scripts
permissions:
  - object: /app
    pattern: "*"
    except: [/app/scripts]
    owner: root
    mode: 777
    type:
      - file
  - object: /app/scripts
    pattern: "*"
    owner: root
    mode: 770
    type:
      - file
hooks:
  BeforeInstall:
    - location: scripts/setup_env.sh
      timeout: 300
      runas: root
#  AfterInstall:
#    - location: scripts/change_permissions.sh
#      timeout: 300
#      runas: root
#
  ApplicationStop:
    - location: scripts/stop_app.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_app.sh
      timeout: 1500
      runas: root
  ValidateService:
    - location: scripts/status_app.sh
      timeout: 300
      runas: root
